export const COUNTRIES = [
  {
    name: "Argentina",
    continent: "América do Sul",
    capital: "Buenos Aires",
    language: "Espanhol",
    population: "46M",
    worldCups: 3,
    independence: 1816,
    climate: "Variado (subtropical a subpolar)",
    gastronomy: "Asado, Empanadas, Mate",
    traditions: "Tango, Carnaval de Gualeguaychú",
    historicalFacts:
      "Vice-reino do Rio da Prata, independência de Espanha em 1816, três títulos mundiais (1978, 1986, 2022).",
  },
  {
    name: "Brasil",
    continent: "América do Sul",
    capital: "Brasília",
    language: "Português",
    population: "215M",
    worldCups: 5,
    independence: 1822,
    climate: "Tropical e equatorial",
    gastronomy: "Feijoada, Churrasco, Acarajé",
    traditions: "Carnaval, Capoeira, Festa Junina",
    historicalFacts:
      "Colônia portuguesa, independência em 1822, cinco títulos mundiais (1958, 1962, 1970, 1994, 2002).",
  },
  {
    name: "França",
    continent: "Europa",
    capital: "Paris",
    language: "Francês",
    population: "68M",
    worldCups: 2,
    independence: 843,
    climate: "Temperado oceânico e continental",
    gastronomy: "Croissant, Baguete, Ratatouille",
    traditions: "Bastille Day, Moda Parisiense",
    historicalFacts:
      "Reino Franco desde 843, Revolução Francesa em 1789, dois títulos mundiais (1998, 2018).",
  },
  {
    name: "Alemanha",
    continent: "Europa",
    capital: "Berlim",
    language: "Alemão",
    population: "84M",
    worldCups: 4,
    independence: 1871,
    climate: "Temperado continental",
    gastronomy: "Schnitzel, Bratwurst, Pretzel",
    traditions: "Oktoberfest, Mercados de Natal",
    historicalFacts:
      "Unificação em 1871, quatro títulos mundiais (1954, 1974, 1990, 2014).",
  },
  {
    name: "Itália",
    continent: "Europa",
    capital: "Roma",
    language: "Italiano",
    population: "60M",
    worldCups: 4,
    independence: 1861,
    climate: "Mediterrâneo e continental",
    gastronomy: "Pizza, Pasta, Risoto",
    traditions: "Carnaval de Veneza, Corrida de Pálio",
    historicalFacts:
      "Unificação italiana em 1861, quatro títulos mundiais (1934, 1938, 1982, 2006).",
  },
  {
    name: "Espanha",
    continent: "Europa",
    capital: "Madri",
    language: "Espanhol",
    population: "47M",
    worldCups: 1,
    independence: 1492,
    climate: "Mediterrâneo e semiárido",
    gastronomy: "Paella, Tapas, Gazpacho",
    traditions: "La Tomatina, Corrida de Touros",
    historicalFacts: "Reino unificado em 1492, um título mundial (2010).",
  },
  {
    name: "Portugal",
    continent: "Europa",
    capital: "Lisboa",
    language: "Português",
    population: "10M",
    worldCups: 0,
    independence: 1143,
    climate: "Mediterrâneo e oceânico",
    gastronomy: "Bacalhau, Pastéis de Nata, Caldo Verde",
    traditions: "Fado, Festa de São João",
    historicalFacts: "Reino fundado em 1143, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Inglaterra",
    continent: "Europa",
    capital: "Londres",
    language: "Inglês",
    population: "56M",
    worldCups: 1,
    independence: 927,
    climate: "Oceânico temperado",
    gastronomy: "Fish and Chips, Roast Beef, Scones",
    traditions: "Changing of the Guard, Bonfire Night",
    historicalFacts:
      "Reino unificado por volta de 927, um título mundial (1966).",
  },
  {
    name: "México",
    continent: "América do Norte",
    capital: "Cidade do México",
    language: "Espanhol",
    population: "130M",
    worldCups: 0,
    independence: 1821,
    climate: "Variado (tropical a árido)",
    gastronomy: "Tacos, Guacamole, Mole",
    traditions: "Día de los Muertos, Mariachi",
    historicalFacts:
      "Independência da Espanha em 1821, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Estados Unidos",
    continent: "América do Norte",
    capital: "Washington D.C.",
    language: "Inglês",
    population: "335M",
    worldCups: 0,
    independence: 1776,
    climate: "Variado (temperado a tropical)",
    gastronomy: "Hambúrguer, BBQ, Apple Pie",
    traditions: "Thanksgiving, Super Bowl",
    historicalFacts:
      "Independência da Grã-Bretanha em 1776, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Canadá",
    continent: "América do Norte",
    capital: "Ottawa",
    language: "Inglês e Francês",
    population: "38M",
    worldCups: 0,
    independence: 1867,
    climate: "Continental e subártico",
    gastronomy: "Poutine, Maple Syrup, Tourtière",
    traditions: "Hockey no gelo, Maple Leaf Tartan",
    historicalFacts: "Domínio britânico em 1867, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Uruguai",
    continent: "América do Sul",
    capital: "Montevidéu",
    language: "Espanhol",
    population: "3.5M",
    worldCups: 2,
    independence: 1825,
    climate: "Temperado oceânico",
    gastronomy: "Asado, Chivito, Mate",
    traditions: "Carnaval de Montevidéu, Candombe",
    historicalFacts:
      "Independência em 1825, dois títulos mundiais (1930, 1950).",
  },
  {
    name: "Colômbia",
    continent: "América do Sul",
    capital: "Bogotá",
    language: "Espanhol",
    population: "52M",
    worldCups: 0,
    independence: 1810,
    climate: "Variado (tropical a frio de montanha)",
    gastronomy: "Arepas, Bandeja Paisa, Sancocho",
    traditions: "Festival de Barranquilla, Festival del Vallenato",
    historicalFacts: "Independência em 1810, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Chile",
    continent: "América do Sul",
    capital: "Santiago",
    language: "Espanhol",
    population: "19M",
    worldCups: 0,
    independence: 1818,
    climate: "Variado (deserto a temperado frio)",
    gastronomy: "Empanadas, Cazuela, Completo",
    traditions: "Cueca, Fiestas Patrias",
    historicalFacts: "Independência em 1818, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Peru",
    continent: "América do Sul",
    capital: "Lima",
    language: "Espanhol",
    population: "33M",
    worldCups: 0,
    independence: 1821,
    climate: "Variado (deserto a tropical)",
    gastronomy: "Ceviche, Lomo Saltado, Anticuchos",
    traditions: "Inti Raymi, Carnaval de Cajamarca",
    historicalFacts: "Independência em 1821, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Japão",
    continent: "Ásia",
    capital: "Tóquio",
    language: "Japonês",
    population: "125M",
    worldCups: 0,
    independence: 660,
    climate: "Temperado e subtropical",
    gastronomy: "Sushi, Ramen, Tempurá",
    traditions: "Sakura, Hanami, Matsuri",
    historicalFacts:
      "Império fundado em 660 a.C., nunca venceu a Copa do Mundo.",
  },
  {
    name: "Coreia do Sul",
    continent: "Ásia",
    capital: "Seul",
    language: "Coreano",
    population: "52M",
    worldCups: 0,
    independence: 1948,
    climate: "Temperado continental",
    gastronomy: "Kimchi, Bibimbap, Bulgogi",
    traditions: "Chuseok, Seollal",
    historicalFacts:
      "República proclamada em 1948, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Austrália",
    continent: "Oceania",
    capital: "Camberra",
    language: "Inglês",
    population: "26M",
    worldCups: 0,
    independence: 1901,
    climate: "Variado (árido a temperado)",
    gastronomy: "Vegemite, Meat Pie, Barramundi",
    traditions: "Australia Day, ANZAC Day",
    historicalFacts: "Federação em 1901, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Marrocos",
    continent: "África",
    capital: "Rabat",
    language: "Árabe e Berbere",
    population: "37M",
    worldCups: 0,
    independence: 1956,
    climate: "Mediterrâneo e árido",
    gastronomy: "Tajine, Couscous, Bastilla",
    traditions: "Festival de Fès, Fantasia",
    historicalFacts:
      "Independência da França em 1956, nunca venceu a Copa do Mundo.",
  },
  {
    name: "Senegal",
    continent: "África",
    capital: "Dakar",
    language: "Francês",
    population: "17M",
    worldCups: 0,
    independence: 1960,
    climate: "Tropical (savana)",
    gastronomy: "Thieboudienne, Yassa, Mafé",
    traditions: "Festival de Dakar, Laamb (luta tradicional)",
    historicalFacts:
      "Independência da França em 1960, nunca venceu a Copa do Mundo.",
  },
];
